version: 2
updates:
  - package-ecosystem: "pip" # For Python packages
    directory: "/" # Adjust to the directory where your requirements.txt or Pipfile is located
    schedule:
      interval: "daily" # Options include daily, weekly, monthly
